---
title: "R Notebook"
output: html_notebook
---

```{r}

if (!require("tesseract")) {
  install.packages("tesseract", repos="http://cran.rstudio.com/") 
  library(tesseract)
}


if (!require("pdftools")) {
  install.packages("pdftools", repos="http://cran.rstudio.com/") 
  library(pdftools)
}



Sys.getenv("R_ARCH")

install.packages("rJava")
library(rJava) # load and attach 'rJava' now

install.packages("devtools")
devtools::install_github("ropensci/tabulizer", args="--no-multiarch")

library(tabulizer)

library(dplyr)
```

#Read text in spanish from pdf
https://ropensci.org/technotes/2017/08/17/tesseract-16/
```{r}
#1.Import a library
tesseract_download("spa")
```


only text from pdf
===============
#2. Convert from "pdf" to "png"
```{r}

pdf_convert("C:/R-Source/4.pdf/corte.pdf", 
                       pages = 2, 
                       dpi = 600, 
                       filenames = "page1.png")
```

#3.Extract text from one page
```{r}
text <- ocr("page1.png",engine = tesseract("spa"))
cat(text)
```



Extract text from one great number of pages
=========================================
```{r}
img_file <- pdftools::pdf_convert("R-intro.pdf", format = 'tiff', pages = 1, dpi = 400)
# Extract text from png image
text <- ocr(img_file)
unlink(img_file)
cat(text)


```

Extract table from pdf (library(tabulizer))
=========================
```{r}
#set path to file
file_pdf <- "C:/R-Source/4.pdf/Cotizaci?n.pdf"

area <- locate_areas(file_pdf, pages = 2)
area

mortgagerates <- extract_tables(file, pages = 3, area = area, guess = FALSE)


out <- extract_tables((file_pdf), pages = 2)
```


```{r}

pdf_subset("~/Documentos/1.R-source/Rolling_Stones_Magazine_TOP500_Songs.pdf",output = "pdfB.pdf", pages = 1:2 )

```



#pdf_Proveedores
```{r}

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Proveedores_JIRA_26-dic-2019.pdf",output = "pdf1.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Proveedores_JIRA_27-dic-2019.pdf",output = "pdf2.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Proveedores_JIRA_19-Feb-2020.pdf",output = "pdf3.pdf")



pdf_combine(c("pdf1.pdf", "pdf2.pdf","pdf3.pdf"), output = "C:/Users/sgarciag/Documents/R-Source/Capacitacion_Proveedores_JIRA.pdf")




```


