---
title: "R Notebook"
output: html_notebook
---
```{r}

if (!require("pdftools")) {
  install.packages("pdftools", repos="http://cran.rstudio.com/") 
  library(pdftools)
}

```


#pdf_Usuarios
WARNING:  pdf_subset Put each file into the same directoty which contain this script .rmd
```{r}

#1. Extract from the source
pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_11-dic-2019 T.temprano.pdf",output = "pdf1.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_11-dic-2019 T.Tarde.pdf",output = "pdf2.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_16-dic-2019.pdf",output = "pdf3.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_17-dic-2019.pdf",output = "pdf4.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_18-dic-2019.pdf",output = "pdf5.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_13-Ene-2020.pdf",output = "pdf6.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_14-Ene-2020.pdf",output = "pdf7.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_15-Ene-2020.pdf",output = "pdf8.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_16-Ene-2020.pdf",output = "pdf9.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_17-Ene-2020.pdf",output = "pdf10.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_20-Ene-2020.pdf",output = "pdf11.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA_23-Ene-2020.pdf",output = "pdf12.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_OTI_JIRA_23-Oct-2019.pdf",output = "pdf13.pdf")

#2.Combine them with the other one
pdf_combine(c("pdf1.pdf", "pdf2.pdf","pdf3.pdf","pdf4.pdf","pdf5.pdf","pdf6.pdf","pdf7.pdf","pdf8.pdf","pdf9.pdf","pdf10.pdf","pdf11.pdf","pdf12.pdf","pdf13.pdf"), output = "C:/Users/sgarciag/Documents/R-Source/Capacitacion_Usuarios_JIRA.pdf")



```

#pdf_Proveedores
```{r}

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Proveedores_JIRA_26-dic-2019.pdf",output = "pdf1.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Proveedores_JIRA_27-dic-2019.pdf",output = "pdf2.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Proveedores_JIRA_19-Feb-2020.pdf",output = "pdf3.pdf")



pdf_combine(c("pdf1.pdf", "pdf2.pdf","pdf3.pdf"), output = "C:/Users/sgarciag/Documents/R-Source/Capacitacion_Proveedores_JIRA.pdf")




```





#pdf Operadores
```{r}
pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Operadores_JIRA_21-Feb-2020 T.Temprano.pdf",output = "pdfA.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/Capacitacion_Operadores_JIRA_21-Feb-2020 T.Tarde.pdf",output = "pdfB.pdf")


pdf_combine(c("pdfA.pdf", "pdfB.pdf"), output = "C:/Users/sgarciag/Documents/R-Source/Capacitacion_Operadores_JIRA2.pdf")

```


#1er anexo
```{r}
pdf_subset("C:/Users/sgarciag/Documents/R-Source/anexo1.pdf",output = "pdfA.pdf")

pdf_subset("C:/Users/sgarciag/Documents/R-Source/hoja2.pdf",output = "pdfB.pdf", pages = 1:2 )


pdf_combine(c("pdfA.pdf", "pdfB.pdf"), output = "C:/Users/sgarciag/Documents/R-Source/1er_anexo.pdf")

```




#2do anexo

```{r}

pdf_subset("C:/Users/sgarciag/Documents/R-Source/extraer_impar.pdf",output = "pdfc.pdf", pages = 1:2 )


pdf_combine(c("pdfc.pdf"), output = "C:/Users/sgarciag/Documents/R-Source/2do_anexo.pdf")

```



#3er anexo

```{r}

pdf_subset("C:/Users/sgarciag/Documents/R-Source/extraer_impar.pdf",output = "pdfg.pdf", pages = 3:4 )

pdf_subset("C:/Users/sgarciag/Documents/R-Source/extraer_par.pdf",output = "pdfh.pdf", pages = 8 )

pdf_subset("C:/Users/sgarciag/Documents/R-Source/extraer_impar.pdf",output = "pdfi.pdf", pages = 5 )

pdf_subset("C:/Users/sgarciag/Documents/R-Source/extraer_par.pdf",output = "pdfj.pdf", pages = 7)

pdf_subset("C:/Users/sgarciag/Documents/R-Source/extraer_impar.pdf",output = "pdfk.pdf", pages = 6)

pdf_subset("C:/Users/sgarciag/Documents/R-Source/extraer_par.pdf",output = "pdfl.pdf", pages = 6 )

pdf_subset("C:/Users/sgarciag/Documents/R-Source/extraer_impar.pdf",output = "pdfm.pdf", pages = 7 )


pdf_combine(c("pdfg.pdf","pdfh.pdf","pdfi.pdf","pdfj.pdf","pdfk.pdf","pdfl.pdf","pdfm.pdf"), output = "C:/Users/sgarciag/Documents/R-Source/3er_anexo.pdf")

```





#4to anexo

```{r}

pdf_subset("C:/Users/sgarciag/Documents/R-Source/extraer_impar.pdf",output = "pdff.pdf", pages = 8:9 )

pdf_combine(c("pdff.pdf"), output = "C:/Users/sgarciag/Documents/R-Source/4to_anexo.pdf")

```







#5to anexo

```{r}

pdf_subset("C:/Users/sgarciag/Documents/R-Source/extraer_impar.pdf",output = "pdfd.pdf", pages = 10:11 )

pdf_subset("C:/Users/sgarciag/Documents/R-Source/extraer_par.pdf",output = "pdfe.pdf",pages = 1)

pdf_combine(c("pdfd.pdf","pdfe.pdf"), output = "C:/Users/sgarciag/Documents/R-Source/5to_anexo.pdf")

```



#Total

```{r}

pdf_subset("C:/Users/sgarciag/Documents/R-Source/1hoja.pdf",output = "pdf1.pdf", pages = 1:2)
pdf_subset("C:/Users/sgarciag/Documents/R-Source/1er_anexo.pdf",output = "pdf2.pdf", pages = 1:3)
pdf_subset("C:/Users/sgarciag/Documents/R-Source/2do_anexo.pdf",output = "pdf3.pdf", pages = 1:2)
pdf_subset("C:/Users/sgarciag/Documents/R-Source/3er_anexo.pdf",output = "pdf4.pdf", pages = 1:8)
pdf_subset("C:/Users/sgarciag/Documents/R-Source/4to_anexo.pdf",output = "pdf5.pdf", pages = 1:2)
pdf_subset("C:/Users/sgarciag/Documents/R-Source/5to_anexo.pdf",output = "pdf6.pdf", pages = 1:3)




pdf_combine(c("pdf1.pdf","pdf2.pdf","pdf3.pdf","pdf4.pdf","pdf5.pdf", "pdf6.pdf"), output = "C:/Users/sgarciag/Documents/R-Source/Acta.pdf")

```
















































