---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

Install Libraries
```{r}
install.packages("readr")
install.packages("tidyverse")
install.packages("tidyr")
install.packages("dplyr")
install.packages("grid")
install.packages("tibble")
install.packages("stringr")
install.packages("writexl")
#it's better
install.packages("lubridate")
```

Calling Libraries
```{r Calling Libraries}
library(tidyverse)
library(dplyr)
library(grid)
library(tibble)
library(tidyr)
library(stringr)
library(readr)

#for writing
library(writexl)

#for working with dates
library(lubridate)
```


I.IMPORTING
1. From a file
```{r}
#We can read from all "sheet" of any excel file
data1<-read.xlsx("C:/R-Source/procesos1.xlsx", sheetName = "Hoja1")
View(data1)

View(Lista_Maestra_de_iniciativas_TI_POI_PETI)
Lista_Maestra_de_iniciativas_TI_POI_PETI

```



III.SAVE
Libraries: write,xlsx (it comes with "xlsxjars" and "rJava" libraries)
```{r VII.SAVE}
#1.lESS THAN 66000 ROWS: use write.xlsx 
write_xlsx(myDf2,"C:/R-Source/back_myDf2.xls")

#1.lESS THAN 66000 ROWS: use 
write.csv(myDf2, "C:/R-Source/back_myDf2.csv") 

```