---
title: "R Notebook"
output: html_notebook
---


```{r}
install.packages("DBI")
install.packages("RMySQL")
install.packages("nycflights13")
```
s
```{r}
library(DBI)
library(RMySQL)
library(nycflights13)
```


I. BASIC OPERATION
=============================
#1, coNNECT and disconnect
```{r}

con = dbConnect(MySQL(),
                user = 'root',
                password = '',
                host = '127.0.0.1',
                dbname='test')

#Once open the conection que can create any database, like the next one 
dbSendQuery(con, "CREATE DATABASE datawarehouse")

dbDisconnect(con)


#CHarge "nycflights13::airports"

dbWriteTable(con, "airports", airports )

#You can overwrite an existing table like this:
#dbWriteTable(connection, "testTable", testTable_2, overwrite=TRUE)

#now showing all tables that exist in "test" db
dbListTables(con)

#now showing all fields that exist in "airports" table
dbListFields(con,"airports")

dbDisconnect(con)
```

#2.DBI functions
```{r}
#1. Import the complete table using dbReadTable(). We can use this method only if the table is not very big.
dbReadTable(con, "airports")

#2. Send query and retrieve results using dgGetQuery(). It can be used to extract specific rows from a table
dbGetQuery(con, "select lat from airports LIMIT 5")

#3. Submit query using dbSendQuery() and fetch results using dbFetch() Let us explore each of the above methods one by one

dbExecute()

```




2.INSERT FROM A DATAFRAME
===================
#1.Create table3 inside "test"
```{r}
dbSendQuery(con, "CREATE table table3
(id INT AUTO_INCREMENT PRIMARY KEY,
faa VARCHAR(50),
name VARCHAR(50));")


```


#2. Basic Insert
```{r}
df1<-airports[c(1,2)]

df1=as.data.frame(df1)


dbWriteTable(con,"table3", df1,row.names=F, append=TRUE)

#to verify
dbReadTable(con, "table3")
dbListFields(con, "table3")

```

#3.Advanced insert
```{r}

dbWriteTable(con,"table3", airports[c(1,2)],row.names=F, append=TRUE)


```



3.UPDATE
=====================
#1.uPDATE

```{r}
dbExecute(con, "update cost_income set income_amount = 6200 where kind_income_id= '1'")  
```

