---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages(dataf)
```


I.CREATE BASIC STRUCTURES
======================
#1. Create a vector 
```{r}
#Vector
vectNumerico<-c(3,1,5,6,3,9)


vectNumerico<-c(2:8)

vectNumerico<-seq(2, 3, by=0.5)

vectNumerico<-rep(1:2, times=3)
vectNumerico


vectString<-c("jose","jesus","walter","Jonh","Julio","Pieree")
vectString

  
```

II.Create a dataframe
======================
#1.From vectors
```{r}
#one colum
df1<-data.frame(y = 1:5)

#Two columns Data frame without column name, base in previous vectors
df2<-data.frame(vectNumerico,vectString)

#Data frame with column name
df2<-data.frame(products=vectNumerico,peopleName=vectString)

```

#2.From scratch  
```{r}

col1 = c(2, 3, 5) 
 col2 = c("aa", "bb", "cc") 
 col3 = c(TRUE, FALSE, TRUE) 
 df3 = data.frame(col1, col2, col3)
 
 
 #Data frame with 3cols x 5rows
  df4 <- data.frame(Nombre=c("Melody","Gian","Johana","Jearson","Jenny"),scores=c(3,1,5,6,3),Menbership=c(11,2,6,7,8))
```



#3. From a "R Data Librerias"
```{r}
data("iris")

#Showing 4 first rows from iris dataset
head(iris,4)

#Showing 5 last rows from iris dataset
tail(iris,5)

#Assign to a variable
df5 <- head(iris,10)
df5
View(df5)

```


#4. From files
```{r}
df6<- read_excel("C:/R-Source/prueba1.xlsx")
View(df6)
```



III. SHOW BASIC FEATURES
=================
#1.Name of columns
```{r}
 #Colnames 
  colnames(df3)
```

#2.Count columns and rows 
```{r}
 
nRowsDf <- nrow(df3)


nColsDf<-ncol(df3)

```


#Class
```{r}
df3$col1
```

# Unique record
```{r}
unique(iris$Species)
```



#Asign column's names
```{r}
names(df1)[1]<-"Nombre"
names(df1)[2]<-"Puntos"


#assign to all 
names(df1) <- c("Magazines", "Comic books", "Fiction")


View(df1)
```




LIST
===============
*Base on "R for data Science", by Hadley Wickham*

# 1.Create and show Lists
```{r}
L1 <- list(c(1, 4), c(8, 4))
L2 <- list(list(1, 8), list(7, 4))
L3 <- list(1, list(2, list(5)))


```

#2. Subsetting ("utils" packages)
```{r}
a <- list(a = 1:3, b = "a string", c = pi, d = list(-1, -5))

str(a[1:2])

```
#3.Assign values to a Dataframe
```{r}
exlist<-as.data.frame(a$a)
```

